#!/bin/sh

cat <<-EOF

Vous pouvez lancer tout module dont vous avez precise le nom (sans le .o en parametre
Type <return> to install modules, then <return> again when you want to stop it
EOF

read junk
insmod /root/modules/rtai_hal.o
insmod /root/modules/rtai_sched.o
insmod /root/modules/rtai_fifos.o
insmod sensor.o

echo "Program is running"
echo "Type <return> to remove modules"
read junk

rmmod sensor
rmmod rtai_fifos
rmmod rtai_sched
rmmod rtai_hal
